version: '2.23.3'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: quanganh123
    ports:
      - 3306:3306
    volumes:
      - ./fashion_project.sql:/docker-entrypoint-initdb.d/fashion_project.sql
    networks:
      - fashion-network

  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin8-container
    depends_on:
      - mysql8-container
    ports:
      - "8100:80"
    environment:
      PMA_HOST: mysql8-container
    networks:
      - fashion-network

  fashion-spring-boot-container:
    container_name: fashion-spring-container
    build:
      context: .
      dockerfile: ./DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - 8080:8080
    networks:
      - fashion-network

networks:
  fashion-network:
    driver: bridge

    #  docker-compose -f DockerCompose.yaml up -d



